name: "Create a GitHub App installation access token"
description: "GitHub Action for creating a GitHub App installation access token"
author: "githubofkrishnadhas"
branding:
  icon: 'activity'
  color: 'gray-dark'
inputs:
  github_app_id:
    description: "Github App ID"
    required: true
  github_app_private_key:
    description: "Github App private key"
  github_account_type:
    description: "Github account user or organization"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_app_id }}
    - ${{ inputs.github_app_private_key }}
    - ${{ inputs.github_account_type }}
