name: "Create a GitHub App installation access token"
description: "GitHub Action for creating a GitHub App installation access token"
author: "githubofkrishnadhas"
branding:
  icon: 'activity'
  color: 'gray-dark'
inputs:
  github_app_id:
    description: "Github App ID"
    required: true
  github_app_private_key:
    description: "Github App private key"
    required: true
  owner:
    description: "The owner of the GitHub App installation. If empty, defaults to the current repository owner"
    required: false
  repositories:
    description: "Comma-separated list of repositories to grant access to"
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_app_id }}
    - ${{ inputs.github_app_private_key }}
    - ${{ inputs.owner }}
    - ${{ inputs.repositories }}
