name: "create github app json web token"
description: "GitHub Action for creating a GitHub App installation access token"
author: "githubofkrishnadhas"
inputs:
  github_app_id:
    description: "Github App ID"
    type: number
    required: true
  github_app_private_key:
    description: "Github App private key"
runs:
  using: 'docker'
  image: 'Dockerfile'